name: chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.1
  permission_handler: ^8.3.0
  image_picker: ^0.8.4+2
  camera: ^0.10.0+2
  geolocator: ^8.2.1
  intl: ^0.17.0
  http: ^0.13.3
  path_provider: ^2.0.2
  shared_preferences: ^2.0.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true